version: '3.5'

# // @info requires `.env.user.hmr.{CURRENT_ENVIRONMENT}` with definition of used environment variables

services:
  ### Workspace Utilities ##################################
  workspace:
    ports:
      - '${HMR_PORT}:${HMR_PORT}'
    environment:
      - HMR_HOST=${HMR_HOST}
      - HMR_PORT=${HMR_PORT}
      - HMR_HOST_DEV_SERVER=${HMR_HOST_DEV_SERVER}
      - HMR_SSL_CERT_PATH=${HMR_SSL_CERT_PATH}
      - HMR_SSL_KEY_PATH=${HMR_SSL_KEY_PATH}
      - HMR_SSL_CAPEM_PATH=${HMR_SSL_CAPEM_PATH}
