stages:
  - stage: 'Release_Staging'
    displayName: 'Release to Staging'
    dependsOn:
      - 'Build'
    condition: eq(variables['stages_enabled__stage_release_staging'], true)
    variables:
      artifactVersionBuildTagFromBuild: $[ stageDependencies.Build.from_source_to_artifact.outputs['artifactVersion.artifactVersionBuildTag'] ]
    jobs:
    - deployment: 'release_to_staging'
      timeoutInMinutes: 15
      cancelTimeoutInMinutes: 5
      pool:
        vmImage: 'ubuntu-18.04'
      environment: 'Staging'
      strategy:
        runOnce:
          deploy:
            steps:

              # //////////////////////////////////////////////////////////////////////
              # // DEBUG

              - bash: |
                  echo "VERSION                                                   = '$(artifactVersionBuildTagFromBuild)'"
                  echo ''
                  echo "STAGING_ENV_SSH_KNOWN_HOST_ENTRY                          = '$(STAGING_ENV_SSH_KNOWN_HOST_ENTRY)'"
                  echo ''
                  echo "STAGING_ENV_USER                                          = '$(STAGING_ENV_USER)'"
                  echo "STAGING_ENV_HOST                                          = '$(STAGING_ENV_HOST)'"
                  echo "STAGING_ENV_SSH_URL                                       = '$(STAGING_ENV_SSH_URL)'"
                  echo ''
                  echo "STAGING_ENV_APP_PATH                                      = '$(STAGING_ENV_APP_PATH)'"
                  echo "STAGING_ENV_URL                                           = '$(STAGING_ENV_URL)'"
                  echo ''
                  echo "db_migration_enabled__stages_release                      = '$(db_migration_enabled__stages_release)'"
                  echo "db_backup_enabled__stage_staging                          = '$(db_backup_enabled__stage_staging)'"
                  echo "app_maintenance_during_deployment_enabled__stage_staging = '$(app_maintenance_during_deployment_enabled__stage_staging)'"
                displayName: 'DEBUG'
                condition: eq(variables['debug_mode__stage_staging_deployment'], true)

              # //////////////////////////////////////////////////////////////////////
              # // Preparation

              - task: InstallSSHKey@0
                inputs:
                  knownHostsEntry: $(STAGING_ENV_SSH_KNOWN_HOST_ENTRY)
                  sshPublicKey: $(ARTIFACT_REPOSITORY_SSH_PUBLIC_KEY)
                  sshKeySecureFile: $(ARTIFACT_REPOSITORY_SSH_KEY_SECURE_FILENAME)
                displayName: 'Preparation: install ssh key'

              - bash: |
                  ssh $(STAGING_ENV_SSH_URL) << SSH_COMMAND
                    cd $(STAGING_ENV_APP_PATH)
                    pwd
                    git fetch --all --tags
                  SSH_COMMAND
                displayName: 'Preparation: fetch current artifacts repository'

              - bash: |
                  ssh $(STAGING_ENV_SSH_URL) << SSH_COMMAND
                    cd $(STAGING_ENV_APP_PATH)
                    php artisan down --render="errors::503" --retry=60
                  SSH_COMMAND
                displayName: 'Preparation: set application into maintenance'
                condition: and(succeeded(), eq(variables['app_maintenance_during_deployment_enabled__stage_staging'], true))

              - bash: |
                  ssh $(STAGING_ENV_SSH_URL) << SSH_COMMAND
                    cd $(STAGING_ENV_APP_PATH)
                    php artisan backup:run --only-db --no-interaction --timeout=120
                  SSH_COMMAND
                displayName: 'Preparation: backup db'
                condition: and(succeeded(), eq(variables['db_backup_enabled__stage_staging'], true))

              # //////////////////////////////////////////////////////////////////////
              # // Deployment

              - bash: |
                  current_artifact_version='$(artifactVersionBuildTagFromBuild)'
                  ssh $(STAGING_ENV_SSH_URL) << SSH_COMMAND
                    cd $(STAGING_ENV_APP_PATH)
                    echo ''
                    if [[ -z "${current_artifact_version}" ]]; then
                      echo -e "ERROR: '\$current_artifact_version' is not defined"
                      exit 1
                    fi
                    echo ''
                    echo -e "INFO:  Current Artifact Version: '${current_artifact_version}'"
                    echo ''
                    git checkout "${current_artifact_version}"
                    git status
                    git --no-pager log -1
                  SSH_COMMAND
                displayName: 'Deployment: install new version'

              - bash: |
                  ssh $(STAGING_ENV_SSH_URL) << SSH_COMMAND
                    cd $(STAGING_ENV_APP_PATH)
                    php artisan migrate --force
                  SSH_COMMAND
                displayName: 'Deployment: migrate database'
                condition: and(succeeded(), eq(variables['db_migration_enabled__stages_release'], true))

              - bash: |
                  ssh $(STAGING_ENV_SSH_URL) << SSH_COMMAND
                    cd $(STAGING_ENV_APP_PATH)
                    php artisan storage:link --relative
                  SSH_COMMAND
                displayName: 'Deployment: link storage'

              - bash: |
                  ssh $(STAGING_ENV_SSH_URL) << SSH_COMMAND
                    cd $(STAGING_ENV_APP_PATH)
                    php artisan up
                  SSH_COMMAND
                displayName: 'Deployment: bootup application'

              - bash: |
                  ssh $(STAGING_ENV_SSH_URL) << SSH_COMMAND
                  (
                    flock -w 10 9 || exit 1
                    echo 'Restarting FPM...';
                    sudo /usr/sbin/service php7.4-fpm reload
                  ) 9>/tmp/fpmlock
                  SSH_COMMAND
                displayName: 'Deployment: restart php fpm for opcache invalidation'

              # //////////////////////////////////////////////////////////////////////
              # // Test

              - bash: |
                  curl -fsSL "${STAGING_ENV_URL}"
                displayName: 'Test: is application up and running'


