name: '$(Build.BuildId)  [$(Build.SourceBranchName)]  '

variables:
  # ///////////////////////////////////////////////////////////////////////////
  # // Project Settings ///////////////////////////////////////////////////////
  - name: "DC_PROJECT_NAME"
    value: ""
  - name: ARTIFACT_REPOSITORY
    value: ""
  - name: ARTIFACT_REPOSITORY_SSH_KNOWN_HOST_ENTRY
    value: ""
  - name: ARTIFACT_REPOSITORY_SSH_PUBLIC_KEY
    value: ""
  - name: ARTIFACT_REPOSITORY_SSH_KEY_SECURE_FILENAME
    value: ""

  # // staging ////////////////////////////////////////////////////////////////
  - name: STAGING_ENV_NAME
    value: "Staging"
  - name: STAGING_ENV_USER
    value: ""
  - name: STAGING_ENV_HOST
    value: ""
  - name: STAGING_ENV_APP_PATH
    value: ""
  - name: STAGING_ENV_URL
    value: ""
  - name: STAGING_ENV_URL_CREDENTIALS
    value: ""
  - name: STAGING_ENV_SSH_KNOWN_HOST_ENTRY
    value: ""

  # // prototype //////////////////////////////////////////////////////////////
  - name: PROTOTYPE_ENV_NAME
    value: "Prototype"
  - name: PROTOTYPE_ENV_USER
    value: ""
  - name: PROTOTYPE_ENV_HOST
    value: ""
  - name: PROTOTYPE_ENV_APP_PATH
    value: ""
  - name: PROTOTYPE_ENV_URL
    value: ""
  - name: PROTOTYPE_ENV_URL_CREDENTIALS
    value: ""
  - name: PROTOTYPE_ENV_SSH_KNOWN_HOST_ENTRY
    value: ""

  # // production /////////////////////////////////////////////////////////////
  - name: PRODUCTION_ENV_NAME
    value: "Production"
  - name: PRODUCTION_ENV_USER
    value: ""
  - name: PRODUCTION_ENV_HOST
    value: ""
  - name: PRODUCTION_ENV_APP_PATH
    value: ""
  - name: PRODUCTION_ENV_URL
    value: ""
  - name: PRODUCTION_ENV_URL_CREDENTIALS
    value: ""
  - name: PRODUCTION_ENV_SSH_KNOWN_HOST_ENTRY
    value: ""

  # ///////////////////////////////////////////////////////////////////////////
  # // ACR Credentials ///////////////////////////////////////////////////////
  - name: ACR_URL
    value: "eteamacr.azurecr.io"
  - name: ACR_SP_APP_ID
    value: "e5e5353d-5315-4873-9f1c-00ac3f6dece3"
  # - name: ACR_SP_APP_PASSWORD # define as secure credential in azure devops ui
  #   value: ""

  # ///////////////////////////////////////////////////////////////////////////
  # // Pipeline Configuration /////////////////////////////////////////////////

  # // Debug - define as secure credential in azure devops ui ////////////////
  # - name: debug_mode__stage_build
  #   value: true
  # - name: debug_mode__stage_staging_deployment
  #   value: true
  # - name: debug_mode__stage_production_deployment
  #   value: true
  # - name: debug_mode__stage_prototype_deployment
  #   value: true

  # // enable pipeline stages ///////////////////////////////////////////////
  # - name: stages_enabled__stage_build
  #   value: true
  # - name: stages_enabled__stage_release_staging
  #   value: true
  # - name: stages_enabled__stage_release_production
  #   value: true
  # - name: stages_enabled__stage_release_prototype
  #   value: true

  # // flags for deactivating tasks /////////////////////////////////////////
  # - name: db_migration_enabled__stages_release
  #   value: true
  # - name: db_backup_enabled__stage_staging
  #   value: true
  # - name: db_backup_enabled__stage_production
  #   value: true
  # - name: db_backup_enabled__stage_prototype
  #   value: true
  # - name: app_maintenance_during_deployment_enabled__stage_staging
  #   value: true
  # - name: app_maintenance_during_deployment_enabled__stage_production
  #   value: true
  # - name: app_maintenance_during_deployment_enabled__stage_prototype
  #   value: true

  - template: variables/testing-variables.yml
  - template: variables/base-variables.yml
  - template: variables/artifact-variables.yml
  - template: variables/staging-variables.yml
  - template: variables/prototype-variables.yml
  - template: variables/production-variables.yml

# // make use of customer project specific build trigger with schema //////////
#     e.g. projectId: 'nvt-01678'
#     trigger branch (master customer project branch):
#       ->> 'nvt-01678-master'
#     feature branches:
#       ->> 'nvt-01678/{IssueID}-p-is-able-to-look-around-and-do-some-stuff'
trigger:
- master

stages:
  - template: 'stages/Build-stage.yml'
  - template: 'stages/Release-Staging-stage.yml'
  - template: 'stages/Release-Prototype-stage.yml'
  - template: 'stages/Release-Production-stage.yml'
