#!/usr/bin/env bash

set -e
set -o pipefail

readonly PROJECT_ROOT="$(pwd)"
readonly FORCE="${FORCE:-false}"

# //////////////////////////////////////////////////////////////////////////////
# Define globals
source "$(dirname "$(realpath -m "${0}")")/library/colors.sh"

link_file() {
  local elements=(${1//::/ })
  local source_file="${elements[0]}"
  local absolute_source_file="${PROJECT_ROOT}/${source_file}"
  local target_file="${elements[1]}"
  local absolute_target_file="${PROJECT_ROOT}/${target_file}"

  if [[ ! -f "${absolute_source_file}" ]]; then
    echo -en "${c_red}"
    echo -e  ">> ERROR: Source file '${absolute_source_file}' not found, resolved from :${c_reset}"
    echo -e  "          '${1}'"
    exit 1
  fi

  if [[ -f "${absolute_target_file}" ]] && [[ "${FORCE}" != 'true' ]]; then
      echo -e  ">> WARN:${c_reset}  Target file '${absolute_target_file}' exists, resolved from:"
      echo -e  "          '${1}'"
      return 0
  fi

  if [[ -f "${absolute_target_file}" ]] && [[ "${FORCE}" == 'true' ]]; then
    rm -f "${absolute_target_file}"
    echo -e  ">> WARN:${c_reset}  Target file '${absolute_target_file}' exists, but was removed"
  fi

  link_command="ln -s ${source_file} ${target_file}"

  eval "${link_command}"

  if [[ "${?}" == "0" ]]; then
      echo -en "${c_lgreen}"
      echo -e  ">> INFO:${c_reset}  Files are succesful linked"
      echo -e  "          '${source_file}' ->> '${target_file}'"
  else
      echo -en "${c_red}"
      echo -e  ">> ERROR: Linking failed${c_reset}"
      echo -e  "          '${link_command}'\n"
      exit 1
  fi

}  

echo "Link laradock-configuration files to project root"
echo 

while read -r file; do link_file "${file}" ; done < <(
  cat <<DEPENDENCIES
  vendor/dennyweiss/laradock-configuration/.env.dc.wordpress::.env.dc
  vendor/dennyweiss/laradock-configuration/docker-compose.wordpress.yml::docker-compose.yml
  vendor/dennyweiss/laradock-configuration/.envrc.default::.envrc
  vendor/dennyweiss/laradock-configuration/requirements.txt::requirements.txt
DEPENDENCIES
)
